% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Feb-2015 14:39:51
%  MATLAB version: 8.3.0.532 (R2014a)
% -------------------------------------------------------------------
saveVarsMat = load('SlopeFields.mat');

L = saveVarsMat.L; % <41x31 double> too many elements

S = saveVarsMat.S; % <41x31 double> too many elements

t = saveVarsMat.t; % <41x31 double> too many elements

y = saveVarsMat.y; % <41x31 double> too many elements

clear saveVarsMat;
